import type { Metadata } from 'next';

import { Header } from '@ui/component/Header';
import '@ui/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased font-roboto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
